# -*- coding: utf-8 -*-
"""Extract_product.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zJYjjqT8NXlMfry445raVNe43XrUChw2
"""

import pandas as pd
import re, nltk, spacy, gensim

makeup_data = pd.read_csv("/content/products.csv")

makeup_data.head()

# Using + operator to combine two columns
makeup_data["brand_product"] = makeup_data['brand'].astype(str) +" "+ makeup_data["name"]
# Remove two columns name is 'C' and 'D'
makeup_data.drop(['product_type', 'img', 'rating','dupes', 'shade_img','price_site', 'view_count', 'description' ], axis=1)

makeup_data['brand_product'].unique()

brand_products = list(makeup_data['brand_product'].unique())

test_string = 'Tom Ford Beauty Shade & Illuminate Lips is gthe best lip gloss in the market, you can try it out'

if any(x in test_string for x in brand_products):
  print(True)

matches = {x for x in brand_products if x in test_string}
matches

